name: keep-services-awake
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend health
        run: curl -fsS -m 20 https://cargocrazee-backend.onrender.com/api/health | head -c 200 || true
      - name: Ping AI service health
        run: curl -fsS -m 20 https://cargocrazee-ai-service.onrender.com/health | head -c 200 || true
      - name: Log timestamp
        run: echo "Pinged at $(date -u) UTC"
